root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -tags=noembed -o ./tmp/main ."
bin = "./tmp/main"
delay = 0
exclude_dir = [
    "assets/scripts",
    "assets/styles",
    "tmp",
    "vendor",
    "node_modules",
]
exclude_file = []
exclude_regex = ["_test\\.go", ".*_templ\\.go", ".*_templ\\.txt"]
exclude_unchanged = true
follow_symlink = true
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "air.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
